- name: Install win-zabbix-agent
  hosts: windows
  remote_user: Administrator
  roles:
    - name: common
      tags:
        - common
    - name: win-zabbix-agent
      tags:
        - win-zabbix-agent
