- name: rpmfile cp
  copy:  src=/work/zabbix-agent-{{ zabbix_agent_version }}.x86_64.rpm  dest=/tmp/

- name: rpm install
  yum: name=/tmp/zabbix-agent-{{ zabbix_agent_version }}.x86_64.rpm  state=present

- name: rpmfile del
  file: path=/tmp/zabbix-agent-{{ zabbix_agent_version }}.x86_64.rpm  state=absent

- name: Set Server ip
  lineinfile: >
    dest=/etc/zabbix/zabbix_agentd.conf
    state=present
    backrefs=yes
    regexp='^Server=.*[0-9]$'
    line='Server={{ zabbix_server_ip }}'

- name: Set ServerActive ip
  lineinfile: >
    dest=/etc/zabbix/zabbix_agentd.conf
    state=present
    backrefs=no
    regexp='^ServerActive=.*[0-9]$'
    line='ServerActive={{ zabbix_server_ip }}:10051'

- name: Set Hostname
  lineinfile: >
    dest=/etc/zabbix/zabbix_agentd.conf
    state=present
    backrefs=yes
    regexp='^Hostname=.*'
    line='Hostname={{ ansible_hostname }}'

- name: start zabbix-agent and enable
  service: name=zabbix-agent state=started enabled=yes
