- name: register zabbix_agentd config Server ip
  shell: cat /etc/zabbix/zabbix_agentd.conf | grep '^Server='
  register: result_Server_ip
  changed_when: false

- name: modify zabbix_agentd config Server ip
  replace:
   dest=/etc/zabbix/zabbix_agentd.conf
   regexp=",{{ zabbix_server_replace_ip }}"
   replace=""
  with_items:
   -  zabbix_server_replace_ip

- name: modify zabbix_agentd config Server ip(when writted for leading host)
  replace:
   dest=/etc/zabbix/zabbix_agentd.conf
   regexp="Server={{ zabbix_server_replace_ip }},"
   replace="Server="
  when: result_Server_ip.stdout.find("Server=zabbix_server_replace_ip")
  with_items:
   -  zabbix_server_replace_ip
   
- name: register zabbix_agentd config ServerActive ip
  shell: cat /etc/zabbix/zabbix_agentd.conf | grep '^ServerActive='
  register: result_ServerActive_ip
  changed_when: false

- name: modify zabbix_agentd config ServerActive ip
  replace:
   dest=/etc/zabbix/zabbix_agentd.conf
   regexp=",{{ zabbix_server_replace_ip }}:10051"
   replace=""
  with_items:
   -  zabbix_server_replace_ip

- name: modify zabbix_agentd config ServerActive ip(when writted for leading host)
  replace:
   dest=/etc/zabbix/zabbix_agentd.conf
   regexp="Server={{ zabbix_server_replace_ip }}:10051,"
   replace="Server="
  when: result_ServerActive_ip.stdout.find("ServerActive=zabbix_server_replace_ip:10051")
  with_items:
   -  zabbix_server_replace_ip
  notify:
    - restart zabbix-agent
